version: "3.8"

networks:
  rocket_chat_network:
    driver: bridge

volumes:
  nginx_certificates: { driver: local }
  nginx_vhost: { driver: local }

services:
  rocketchat:
    image: ${IMAGE:-registry.rocket.chat/rocketchat/rocket.chat}:${RELEASE:-latest}
    restart: always
    environment:
      MONGO_URL: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_ADVERTISED_HOSTNAME}:${MONGODB_PORT_NUMBER}/${MONGODB_DATABASE}?authSource=${MONGODB_DATABASE}&replicaSet=${MONGODB_REPLICA_SET_NAME}"
      MONGO_OPLOG_URL: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_ADVERTISED_HOSTNAME}:${MONGODB_PORT_NUMBER}/local?authSource=${MONGODB_DATABASE}&replicaSet=${MONGODB_REPLICA_SET_NAME}&maxPoolSize=10&minPoolSize=5"
      ROOT_URL: ${ROOT_URL:-https://localhost}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}
      CACHE_SIZE: 512MB # Enable caching for better responsiveness
    expose:
      - ${PORT:-3000}
#    depends_on:
#      - mongodb
    networks:
      - rocket_chat_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" # Rotate logs to prevent excessive disk usage

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rocketchat
    networks:
      - rocket_chat_network
