version: "3.8"

networks:
  rocket_chat_network:
    driver: bridge

services:
  # Node Exporter for Prometheus
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
    - '9100:9100' # Port untuk Node Exporter
    restart: always
    networks:
    - rocket_chat_network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9100/metrics || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3

  # Nginx Prometheus Exporter
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: prometheus-nginx-exporter
    restart: always
    env_file: .env
    command:
    - '-nginx.scrape-uri=http://nginx/stub_status'
    ports:
    - '9113:9113' # Port untuk Nginx Prometheus Exporter
    networks:
    - rocket_chat_network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9113/metrics || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      SCRAPE_URI: "http://nginx/stub_status"

  # Rocket.Chat Application Service
  rocketchat:
    image: ${IMAGE:-registry.rocket.chat/rocketchat/rocket.chat}:${RELEASE:-latest}
    restart: always
    environment:
      MONGO_URL: "mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@${MONGODB_ADVERTISED_HOSTNAME}:${MONGODB_PORT_NUMBER}/${MONGODB_DATABASE}?authSource=${MONGO_AUTH_SOURCE}&replicaSet=${MONGODB_REPLICA_SET_NAME}"
      MONGO_OPLOG_URL: "mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@${MONGODB_ADVERTISED_HOSTNAME}:${MONGODB_PORT_NUMBER}/local?authSource=${MONGO_AUTH_SOURCE}&replicaSet=${MONGODB_REPLICA_SET_NAME}"
      ROOT_URL: ${ROOT_URL:-https://localhost}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}
    ports:
    - ${PORT:-3000}:${PORT:-3000} # Port untuk Rocket.Chat
    networks:
    - rocket_chat_network

  # Nginx Service to reverse proxy Rocket.Chat
  nginx:
    image: nginx:latest
    restart: "no"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/certs:/etc/nginx/certs:ro
    ports:
    - "80:80" # Port HTTP untuk Nginx
    - "443:443" # Port HTTPS untuk Nginx
    - "9200:9100" # Ganti port 9100 agar tidak terjadi konflik dengan node_exporter
    - "9220:9113" # Ganti port 9113 agar tidak terjadi konflik dengan nginx-prometheus-exporter
    - "9216:9216" # Port tambahan yang tidak berbenturan
    depends_on:
    - rocketchat
    networks:
    - rocket_chat_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - '9099:9090'
    volumes:
    - ./prometheus:/etc/prometheus
    - ./prometheus/data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--web.enable-lifecycle'
    restart: always
    user: root
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:9090/-/ready || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
    - rocket_chat_network
