- name: Synchronize Rocket.Chat containerization files
  ansible.posix.synchronize:
    src: "../../templates/azzuri-dev/separated-mongodb/"
    dest: "/home/{{ ansible_user }}/rocket-chat/"
    mode: push
    recursive: yes

- name: Create .env file for MongoDB
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/rocket-chat/.env"
    content: |
      MONGODB_VERSION=6.0
      MONGODB_REPLICA_SET_NAME=rs0
      MONGODB_ADVERTISED_HOSTNAME={{ ip_db_server }}
      MONGODB_ENABLE_JOURNAL=true
      ALLOW_EMPTY_PASSWORD=no
      MONGODB_ROOT_USER=admin
      MONGODB_ROOT_PASSWORD=passworddevelopmentservermongodb12
      MONGODB_REPLICA_SET_KEY=3F1FCCBS0RhyuUm3AHcfbIQVYBqNPujFd2RqtvDxRL5g2HT0QVaJFoje0ws+L7
      MONGODB_HOST={{ ip_db_server }}
      MONGODB_PORT_NUMBER=27017
      MONGODB_DATABASE=rocketchat
      MONGO_AUTH_SOURCE=admin
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Ensure .env file exists and is not empty
  ansible.builtin.stat:
    path: "/home/{{ ansible_user }}/rocket-chat/.env"
  register: env_file_stat

- name: Fail if .env file does not exist or is empty
  ansible.builtin.fail:
    msg: ".env file does not exist or is empty. Please check the creation process."
  when: env_file_stat.stat.exists == false or env_file_stat.stat.size == 0

- name: Debug the status of .env file
  ansible.builtin.debug:
    msg: ".env file is present and has content."
  when: env_file_stat.stat.exists == true and env_file_stat.stat.size > 0

