- name: Apply monitoring setup role
  ansible.builtin.include_role:
    name: "monitoring"

# - name: Ensure Docker Compose is up for the monitoring frontend (nginx server)
#   ansible.builtin.shell:
#     cmd: |
#       docker compose -f /home/{{ ansible_user }}/monitoring_config/target.yml up -d
#     executable: /bin/bash
#   when: "'tag_nginx_server' in group_names"

- name: Ensure Docker Compose is up for MongoDB server monitoring
  ansible.builtin.shell:
    cmd: |
      docker compose -f /home/{{ ansible_user }}/monitoring_config/mongodb.yml up -d
    executable: /bin/bash
  when: "'tag_db_server' in group_names"

- name: Setup Rocket.Chat server for monitoring application using Docker Compose
  ansible.builtin.shell: >
    docker compose -f /home/{{ ansible_user }}/monitoring_config/monitoring.yml up -d
  register: docker_compose_up
  changed_when: "'Starting' in docker_compose_up.stdout or 'Creating' in docker_compose_up.stdout"
  when: "'tag_monitoring_server' in group_names"
