# Global Configurations
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  scrape_timeout: 10s # Timeout for scraping a target.

# Define alerting rules file
rule_files:
- alert_rules.yml

# Define alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: [ 'alertmanager:9093' ]

# Scraping configurations
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: [ 'node-exporter:9100' ]
    labels:
      job: 'node_exporter'
      instance: 'nginx_server'
  - targets: [ 'nginx-prometheus-exporter:9113' ]
    labels:
      job: 'nginx_exporter'
      instance: 'nginx_server'
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: instance
  - source_labels: [ job ]
    target_label: job

- job_name: 'nginx'
  scrape_interval: 10s
  static_configs:
  - targets: [ 'nginx:433' ]
    labels:
      job: 'nginx'
      instance: 'nginx_server'
  relabel_configs:
  - source_labels: [ __address__ ]
    target_label: instance
# - job_name: 'mongodb'
#   scrape_interval: 30s
#   static_configs:
#     - targets: ['mongodb-exporter:9216']
#       labels:
#         job: 'mongodb_exporter'
#         instance: 'mongodb_server'
#   relabel_configs:
#     - source_labels: [__address__]
#       target_label: instance
