global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'from@mail.com'
  smtp_auth_username: 'juniyasyos@gmail.com'
  smtp_auth_password: 'password'
  resolve_timeout: 5m

route:
  group_by: [ 'alertname', 'severity' ]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  receiver: 'default'

  routes:
  - matchers:
    - severity = "critical"
    receiver: 'PagerDuty Alert'
    group_wait: 5s
    group_interval: 5s
  - matchers:
    - severity = "warning"
    receiver: 'Slack Alert'
    group_wait: 60s
    group_interval: 60s

receivers:
- name: 'default'
  email_configs:
  - to: 'to@mail.com'
    headers:
      subject: 'Alert: {{ .CommonLabels.alertname }}'
    html: |
      <h1>{{ .CommonLabels.alertname }} Alert</h1>
      <p><strong>Status:</strong> {{ .Status }}</p>
      <p><strong>Details:</strong> {{ .Annotations.description }}</p>
      <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
- name: 'PagerDuty Alert'
  pagerduty_configs:
  - routing_key: 'your-pagerduty-routing-key'
    description: '{{ .Annotations.summary }}'
    details:
      alertname: '{{ .CommonLabels.alertname }}'
      severity: '{{ .Labels.severity }}'
- name: 'Slack Alert'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
    channel: '#alerts'
    text: |
      *Alert:* {{ .CommonLabels.alertname }}
      *Status:* {{ .Status }}
      *Details:* {{ .Annotations.description }}
      *Severity:* {{ .Labels.severity }}
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'

inhibit_rules:
- source_matchers:
  - severity = "critical"
  target_matchers:
  - severity = "warning"
  equal: [ 'alertname', 'instance' ]
