apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # url: http://prometheus:9099
    url: http://44.214.187.241:9099
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: "15s"
