---
- name: Setup global configuration for Rocket.Chat
  hosts: tag_monitoring_server, tag_nginx_server
  become: true
  gather_facts: true

  tasks:
  - name: Apply Monitoring setup
    ansible.builtin.include_role:
      name: "monitoring"

  - name: Ensure Docker Compose is up
    ansible.builtin.shell:
      cmd: |
        docker compose -f /home/{{ ansible_user }}/monitoring_config/target.yml up -d
    args:
      executable: /bin/bash
    when: "'tag_nginx_server' in group_names"

  - name: Setup Rocket.Chat server using Docker Compose
    ansible.builtin.shell: >
      docker compose -f /home/{{ ansible_user }}/monitoring_config/monitoring.yml up -d
    register: docker_compose_up
    changed_when: "'Starting' in docker_compose_up.stdout or 'Creating' in docker_compose_up.stdout"
    when: "'tag_monitoring_server' in group_names"