name: IaC Validation & Auto-Format Workflow

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  terraform:
    name: Terraform Validation & Auto-Format
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Check and Correct Terraform Format
      - name: Terraform Format Correction
        id: format
        run: |
          terraform fmt -recursive
          git diff --name-only --exit-code || echo "::set-output name=changed::true"
        continue-on-error: true

      # Step 5: Validate Terraform Configuration
      - name: Terraform Validate
        run: terraform validate

      # # Step 6: Create PR for formatting changes
      # - name: Create Pull Request
      #   if: steps.format.outputs.changed == 'true'
      #   uses: peter-evans/create-pull-request@v7
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
      #     branch: auto-terraform-format
      #     base: main
      #     commit-message: "chore: Auto-correct Terraform formatting"
      #     title: "chore: Auto-correct Terraform formatting"
      #     body: |
      #       This PR includes automatic corrections for Terraform formatting issues.
      #     delete-branch: false
